<?php

/**
 * BaseProjectStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Project $Project
 * 
 * @method integer       getId()      Returns the current record's "id" value
 * @method string        getName()    Returns the current record's "name" value
 * @method Project       getProject() Returns the current record's "Project" value
 * @method ProjectStatus setId()      Sets the current record's "id" value
 * @method ProjectStatus setName()    Sets the current record's "name" value
 * @method ProjectStatus setProject() Sets the current record's "Project" value
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProjectStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orangepm_project_status');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'id',
             'foreign' => 'projectStatusId'));
    }
}