<?php

/**
 * BaseStoryStatusChange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $storyId
 * @property string $status
 * @property date $actionDate
 * @property Story $Story
 * 
 * @method integer           getId()         Returns the current record's "id" value
 * @method integer           getStoryId()    Returns the current record's "storyId" value
 * @method string            getStatus()     Returns the current record's "status" value
 * @method date              getActionDate() Returns the current record's "actionDate" value
 * @method Story             getStory()      Returns the current record's "Story" value
 * @method StoryStatusChange setId()         Sets the current record's "id" value
 * @method StoryStatusChange setStoryId()    Sets the current record's "storyId" value
 * @method StoryStatusChange setStatus()     Sets the current record's "status" value
 * @method StoryStatusChange setActionDate() Sets the current record's "actionDate" value
 * @method StoryStatusChange setStory()      Sets the current record's "Story" value
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseStoryStatusChange extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orangepm_story_status_change');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('story_id as storyId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('action_date as actionDate', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}