<?php

/**
 * BaseStory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property integer $estimation
 * @property string $name
 * @property string $date_added
 * @property boolean $deleted
 * @property Project $Project
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getProjectId()  Returns the current record's "project_id" value
 * @method integer getEstimation() Returns the current record's "estimation" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getDateAdded()  Returns the current record's "date_added" value
 * @method boolean getDeleted()    Returns the current record's "deleted" value
 * @method Project getProject()    Returns the current record's "Project" value
 * @method Story   setId()         Sets the current record's "id" value
 * @method Story   setProjectId()  Sets the current record's "project_id" value
 * @method Story   setEstimation() Sets the current record's "estimation" value
 * @method Story   setName()       Sets the current record's "name" value
 * @method Story   setDateAdded()  Sets the current record's "date_added" value
 * @method Story   setDeleted()    Sets the current record's "deleted" value
 * @method Story   setProject()    Sets the current record's "Project" value
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseStory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orangepm_story');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('estimation', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_added', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}