<?php

/**
 * BaseTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $storyId
 * @property decimal $effort
 * @property clob $description
 * @property string $ownedBy
 * @property integer $status
 * @property Story $Story
 * @property TaskStatus $TaskStatus
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getName()        Returns the current record's "name" value
 * @method integer    getStoryId()     Returns the current record's "storyId" value
 * @method decimal    getEffort()      Returns the current record's "effort" value
 * @method clob       getDescription() Returns the current record's "description" value
 * @method string     getOwnedBy()     Returns the current record's "ownedBy" value
 * @method integer    getStatus()      Returns the current record's "status" value
 * @method Story      getStory()       Returns the current record's "Story" value
 * @method TaskStatus getTaskStatus()  Returns the current record's "TaskStatus" value
 * @method Task       setId()          Sets the current record's "id" value
 * @method Task       setName()        Sets the current record's "name" value
 * @method Task       setStoryId()     Sets the current record's "storyId" value
 * @method Task       setEffort()      Sets the current record's "effort" value
 * @method Task       setDescription() Sets the current record's "description" value
 * @method Task       setOwnedBy()     Sets the current record's "ownedBy" value
 * @method Task       setStatus()      Sets the current record's "status" value
 * @method Task       setStory()       Sets the current record's "Story" value
 * @method Task       setTaskStatus()  Sets the current record's "TaskStatus" value
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orangepm_task');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('story_id as storyId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('effort', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('owned_by as ownedBy', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TaskStatus', array(
             'local' => 'status',
             'foreign' => 'id',
             'onDelete' => 'set null'));
    }
}