<?php

/**
 * BaseProjectInformationLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $link_name
 * @property string $link
 * @property integer $project_id
 * @property Doctrine_Collection $Project
 * 
 * @method integer                 getId()         Returns the current record's "id" value
 * @method string                  getLinkName()   Returns the current record's "link_name" value
 * @method string                  getLink()       Returns the current record's "link" value
 * @method integer                 getProjectId()  Returns the current record's "project_id" value
 * @method Doctrine_Collection     getProject()    Returns the current record's "Project" collection
 * @method ProjectInformationLinks setId()         Sets the current record's "id" value
 * @method ProjectInformationLinks setLinkName()   Sets the current record's "link_name" value
 * @method ProjectInformationLinks setLink()       Sets the current record's "link" value
 * @method ProjectInformationLinks setProjectId()  Sets the current record's "project_id" value
 * @method ProjectInformationLinks setProject()    Sets the current record's "Project" collection
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProjectInformationLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orangepm_project_info_links');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('link_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}