<?php

/**
 * ProjectUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectUser');
    }
}