<?php

/**
 * StoryStatusChangeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryStatusChangeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoryStatusChangeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoryStatusChange');
    }
}