<?php

/**
 * ProjectLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectLog');
    }
}