<?php

/**
 * ProjectInformationLinksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectInformationLinksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectInformationLinksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectInformationLinks');
    }
}