<?php

/**
 * ProjectProgressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectProgressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectProgressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectProgress');
    }
}