<?php

/**
 * ProjectStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectStatus');
    }
}