<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangepm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class User extends BaseUser
{
    const USER_TYPE_SUPER_ADMIN = 1;
    const USER_TYPE_PROJECT_ADMIN = 2;
    const USER_TYPE_PROJECT_MEMBER = 3;
    
    const FLAG_ACTIVE = 1;
    const FLAG_DELETED = 0;
    
}
