Project:
  actAs: [Timestampable]
  tableName: orangepm_project
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string(255)
    deleted: { type: boolean, notnull: true, default: 1 }
 
Story:
  actAs: [Timestampable]
  tableName: orangepm_story
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    project_id: integer
    estimation: integer
    name: string(255)
    date_added: string(255)
    deleted: { type: boolean, notnull: true, default: 1 }
  relations:
    Project:
      onDelete: CASCADE
      local: project_id	
      foreign: id	
