Project:
  actAs: [Timestampable]
  tableName: orangepm_project
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string(255)
    deleted: { type: boolean, notnull: true, default: 1 }
 
Story:
  actAs: [Timestampable]
  tableName: orangepm_story
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    project_id: integer
    estimation: { type: integer, notnull: false }
    name: string(255)
    date_added: date
    status: string(255)
    accepted_date: { type: date, notnull: false }
    deleted_date: {type: date }
    deleted: { type: boolean, notnull: true, default: 1 }
  relations:
    Project:
      onDelete: CASCADE
      local: project_id	
      foreign: id

ProjectProgress:
  actAs: [Timestampable]
  tableName: orangepm_project_progress
  columns:
    project_id:
      type: integer
      primary: true
    accepted_date:
      type: date
      primary: true
    work_completed: integer
    unit_of_work: integer

